swipe:
  4:
    right:
      command: "xdotool key super+Left"
    left:
      command: "xdotool key super+Right"
    up:
      command: "xdotool key shift+super+x"
pinch:
  3:
    in:
      command: "xdotool key shift+super+x"
  4:
    in:
      command: "xdotool key super+e"
